language: scala

scala:
  - 2.9.3
  - 2.10.4
  - 2.11.8

script:
  - BongoSort.scala
  - BubbleSort.scala
  - InsertionSort.scala
  - QuickSort.scala
  - RecursiveInsertion.scala
  - SelectionSort.scala
